export const landingPlanetsData = [
  {
    "id": "0",
    "name": "Unknown",
    "region": "Unknown",
    "sector": "Unknown",
    "system": "Unknown",
    "terrain": ["Unknown"],
    "climate": ["Unknown"],
    "population": "Unknown",
    "notable_residents": [],
    "affiliationId": "0",
    "imageUrl": "unknown.png",
    "appearances": [],
    "imagePlaceholder": "#555555"
  },
  {
    "id": "1",
    "name": "Tatooine",
    "region": "Outer Rim Territories",
    "sector": "Arkanis",
    "system": "Tatoo system",
    "terrain": ["Desert"],
    "climate": ["Arid"],
    "population": "200000",
    "notable_residents": ["1", "2", "10"],
    "affiliationId": "0",
    "imageUrl": "tatooine.png",
    "appearances": ["1", "2", "3", "4", "5", "6"],
    "imagePlaceholder": "#e5d9b2"
  },
  {
    "id": "2",
    "name": "Alderaan",
    "region": "Core Worlds",
    "sector": "Alderaan sector",
    "system": "Alderaan system",
    "terrain": ["Grasslands", "Mountains"],
    "climate": ["Temperate"],
    "population": "2000000000",
    "notable_residents": ["3"],
    "affiliationId": "1",
    "appearances": ["1", "3", "4"],
    "imageUrl": "alderaan.png",
    "imagePlaceholder": "#82a8c0",
    "destroyed": true
  },
  {
    "id": "8",
    "name": "Naboo",
    "region": "Mid Rim",
    "sector": "Chommell sector",
    "system": "Naboo system",
    "terrain": ["Grasslands", "Hills", "Swamps", "Forests"],
    "climate": ["Temperate"],
    "population": "4500000000",
    "notable_residents": ["8", "21"],
    "affiliationId": "3",
    "imageUrl": "naboo.png",
    "appearances": ["1", "2", "3", "4", "5", "6"],
    "imagePlaceholder": "#94c993"
  },
  {
    "id": "10",
    "name": "Kamino",
    "region": "Extragalactic",
    "sector": "Wild Space",
    "system": "Kamino system",
    "terrain": ["Ocean"],
    "climate": ["Stormy", "Rainy"],
    "population": "1000000000",
    "notable_residents": ["9"],
    "affiliationId": "3",
    "appearances": ["5"],
    "imageUrl": "kamino.png",
    "imagePlaceholder": "#2e3b56"
  },
];
